### ISSUE TITLE
changer  .anyRequest().permitAll() en  ".anyRequest().authenticated() " afin que les accès aux ressources qui ne sont pas autorisées exige une authentification au préalable

### ISSUE THREAD

**Issue by iamntieche** [alhasapi/bookish#2]
https://github.com/alhasapi/bookish/blob/a3adceb72c2abf3044a1b21e2cfc1e62bd6dc2a8/src/main/java/com/alhasapi/book/security/SecurityConfig.java#L57

**Comment by alhasapi** [comment]
Oh oui. Je prevois d'ecrire quelques testes afin de pas oublier.
Merci pour tes remarques.
